const getPeoplePages = () => [
  {
    module: "kyle",
    path: `kyle`,
    componentPath: `./src/components/People/index.js`,
    context: {
      seoTitle: "Happy birthday, Kyle! 🥳",
      password: "shoti",
      name: "Kyle",
      content: `<div class="is-size-5"><p>Happy birthday!! Just wanted to say na you're a rlly solid person and it sucks that I wasn't able to get to know u more back when u were still in MG (esp those homebuddies days) 🥺</p><p class="mt-1">Anw, hope u enjoy d sashimi and the rest of your day!!</p><article class="message is-warning mt-2"><div class="message-body is-size-6"><p>P.S. I'm a kind of person that hates 'what ifs' and a sucker for the 'what could be', mostly YOLO mindset haha. With that being said, I just wanted to let u know na I like you! (aka this is me shooting my shot and asking you out hahahu)</p><p class="mt-1">I rarely shoot my shots bc I rlly take some time first to confirm with myself na I like someone, and as anyone else naman, I get so anxious when I finally tell someone that I have feelings for them so I try to avoid that as much as I can hahaha. But no pressure ah, please know that it would be totally okay if you say no!! I just really wanted to let you know that you're kewl and awesome and I really admire and appreciate you.</p><p class="mt-1">If you'll be g to habol this feb 14 or even just take a chance on me in general, that would be rlly cool but if not, like I said, that's oks lang din! haha tho thank u for giving me the opportunity to be extra like dis 😄 (also pls ignore na the main website, I needed a place lang where I can put this HAHA)</p></div></article>`,
      // content: `<div class="is-size-5"><p>Happy birthday!! Just wanted to say na you're a rlly solid person and it sucks that I wasn't able to get to know u more back when u were still in MG (esp those homebuddies days) 🥺</p><p class="mt-1">Anw, I was supposed to send over some sashimi but I didn't know na you live far away na pala hahaha hope u enjoy the rest of your day tho!!</p><article class="message is-warning mt-2"><div class="message-body is-size-6"><p>P.S. I'm a kind of person that hates 'what ifs' and a sucker for the 'what could be', mostly YOLO mindset haha. With that being said, I just wanted to let u know na I like you! (aka this is me shooting my shot and asking you out hahahu)</p><p class="mt-1">I rarely shoot my shots bc I rlly take some time first to confirm with myself na I like someone, and as anyone else naman, I get so anxious when I finally tell someone that I have feelings for them so I try to avoid that as much as I can hahaha. But no pressure ah, please know that it would be totally okay if you say no!! I just really wanted to let you know that you're kewl and awesome and I really admire and appreciate you.</p><p class="mt-1">If you'll be g to habol this feb 14 or even just take a chance on me in general, that would be rlly cool but if not, like I said, that's oks lang din! haha tho thank u for giving me the opportunity to be extra like dis 😄 (also pls ignore na the main website, I needed a place lang where I can put this HAHA)</p></div></article>`,
    },
  },
]

module.exports = { getPeoplePages }
